[package]
name = "dht20-exporter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
metrics-util = "0.19.0"

rppal = { version = "0.22.1", features = ["hal"] }