name: CI
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: ["arm-unknown-linux-gnueabihf", "aarch64-unknown-linux-gnu"]
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions-rust-lang/setup-rust-toolchain@v1
         with:
           target: ${{ matrix.target }}
       - name: Debug build
         run: cargo build
       - name: Release build
         run: cargo build --release